server {
  listen 80;
  server_name _;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $api_gateway api-gateway:8080;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://$api_gateway$request_uri;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Correlation-ID $request_id;
  }

  location /health {
    proxy_pass http://$api_gateway/health;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
